environment:
  flutter: stable
  xcode: latest

triggering:
  events:
    - push
    - pull_request

branch_patterns:
  - pattern: '*'
  - include: true

workflows:
  test:
    name: Test Workflow
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Run tests
        script: |
          flutter test