environment:
  flutter: stable
  xcode: latest

branch_patterns:
  - pattern: '*'
    include: true
    source: true

workflows:
  build:
    name: Build Workflow
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

  test:
    name: Test Workflow
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Run tests
        script: |
          flutter test --coverage

  publishing:
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Publish artifacts
        script: |
          mkdir -p artifacts
          cp -r coverage/lcov.info artifacts/
