environment:
  flutter: stable
  xcode: latest

triggering:
  events:
    - push
    - pull_request

branch_patterns:
  - pattern: '*'
    include: true

workflows:
  build:
    name: Build Workflow
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

      - name: Build iOS
        script: |
          flutter build ios --release

  test:
    name: Test Workflow
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Run tests
        script: |
          flutter test --coverage

  publishing:
    scripts:
      - name: Publish artifacts
        script: |
          mkdir -p artifacts
          cp -r coverage/lcov.info artifacts/
