environment:
  flutter: stable
  xcode: latest

branch_patterns:
  - pattern: '*'
    include: true
    source: true

workflows:
  test:
    name: Test Workflow
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Run tests
        script: |
          flutter test --coverage
    artifacts:
      - coverage/lcov.info

  build:
    name: Build Workflow
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Building Android
        script: |
          flutter build apk --release

      - name: Build iOS
        script: |
          flutter build ios --debug --no-codesign

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/iphoneos/Runner.app
