// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC48Flnd6CF1tCVbhjmhTT63pwwmsRx1kg',
    appId: '1:39874109414:web:478fbbe2e2675f9c854027',
    messagingSenderId: '39874109414',
    projectId: 'task-manager-app-691c2',
    authDomain: 'task-manager-app-691c2.firebaseapp.com',
    storageBucket: 'task-manager-app-691c2.appspot.com',
    measurementId: 'G-T7FXWQ6PKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1kVZQWcxHH7ma-YFShXveu9H9auu9VXU',
    appId: '1:39874109414:android:5e5315fcd25466b4854027',
    messagingSenderId: '39874109414',
    projectId: 'task-manager-app-691c2',
    storageBucket: 'task-manager-app-691c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHbGjoLgTNc5Bw5Y7TIa2amrmQha1-fZg',
    appId: '1:39874109414:ios:fdee02d03705f32d854027',
    messagingSenderId: '39874109414',
    projectId: 'task-manager-app-691c2',
    storageBucket: 'task-manager-app-691c2.appspot.com',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHbGjoLgTNc5Bw5Y7TIa2amrmQha1-fZg',
    appId: '1:39874109414:ios:fdee02d03705f32d854027',
    messagingSenderId: '39874109414',
    projectId: 'task-manager-app-691c2',
    storageBucket: 'task-manager-app-691c2.appspot.com',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC48Flnd6CF1tCVbhjmhTT63pwwmsRx1kg',
    appId: '1:39874109414:web:936d6ae6b377c382854027',
    messagingSenderId: '39874109414',
    projectId: 'task-manager-app-691c2',
    authDomain: 'task-manager-app-691c2.firebaseapp.com',
    storageBucket: 'task-manager-app-691c2.appspot.com',
    measurementId: 'G-MRQVB62D1P',
  );
}
